apiVersion: v1
kind: Service
metadata:
  name: k8s-grpc
  labels:
    app: k8s-grpc
spec:
  type: ClusterIP
  selector:
    app: k8s-grpc
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
